[tool.isort]
force_sort_within_sections = true  # Ensures sorting inside sections while keeping comments
lines_between_sections = 1  # Keeps separation for readability
known_first_party = ["api", "gpx", "utils", "types"]
known_third_party = ["numpy", "gpkit"]
