[tool.isort]
force_sort_within_sections = true  # Ensures sorting inside sections while keeping comments
lines_between_sections = 1  # Keeps separation for readability
known_first_party = []
known_third_party = ["numpy", "gpkit"]

[tool.pytest.ini_options]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
testpaths = [
    "test",
]
addopts = "--maxfail=3 --disable-warnings"